# Part 1

### Arithmetic

In [1]:
1

1

In [2]:
1.0

1.0

In [3]:
1 + 1

2

In [4]:
1 * 3

3

In [5]:
2 ** 4

16

### Mathematical Order of Operations

PEMDAS - Parenthesis, Exponent, Multiplication, Division, Addition, Substraction

In [6]:
(2 + 3) * 5 + 5

30

### Mod (Reminder)

In [7]:
4 % 2

0

In [8]:
3 % 2

1

### Variable

In [9]:
var = 2

In [10]:
var

2

In [11]:
x = 2
y = 3

In [12]:
z = x + y
z

5

In [13]:
num_of_var = 2

In [14]:
num_of_var

2

### Strings

In [15]:
'single quote'

'single quote'

In [16]:
"double quote"

'double quote'

In [17]:
"I can't go"

"I can't go"

In [18]:
x = 'hello'

In [19]:
x

'hello'

In [20]:
print(x)

hello


In [21]:
num = 12

In [22]:
name = 'Sam'

In [23]:
"My Name is {} and my age is {}".format(name, num)

'My Name is Sam and my age is 12'

### Indexing Strings

In [24]:
x

'hello'

In [25]:
x[0]

'h'

In [26]:
x[4]

'o'

In [27]:
x[-1]

'o'

In [28]:
s = 'abcdefghijk'

In [29]:
s[0:3]

'abc'

In [30]:
s[:3]

'abc'

### Lists

In [31]:
[1,2,3]

[1, 2, 3]

In [32]:
['a','b','c']

['a', 'b', 'c']

In [33]:
my_list = ['a','b','c']

In [34]:
my_list.append('d')

In [35]:
my_list

['a', 'b', 'c', 'd']

In [36]:
num = [1,2,3]

In [37]:
num.append(my_list)

In [38]:
num # nested list

[1, 2, 3, ['a', 'b', 'c', 'd']]

In [39]:
num[0]

1

In [40]:
num[0:3]

[1, 2, 3]

In [41]:
num[0:4]

[1, 2, 3, ['a', 'b', 'c', 'd']]

In [42]:
num[0:4][3]

['a', 'b', 'c', 'd']

In [43]:
num[0:4][3][0]

'a'

# Part 2

### Dictionaries (Key, Value Pair)

In [44]:
d = {'key1':'value','key2':'123','key3':'abc'}

In [45]:
d

{'key1': 'value', 'key2': '123', 'key3': 'abc'}

In [46]:
d['key1']

'value'

In [47]:
d['key2']

'123'

In [48]:
d['key3']

'abc'

In [49]:
c = {'k1':[1,2,3]}

In [50]:
c

{'k1': [1, 2, 3]}

In [51]:
c['k1']

[1, 2, 3]

In [52]:
c['k1'][0]

1

In [53]:
b = {'k1':{'innerkey':[1,2,3]}}

In [54]:
b['k1']['innerkey']

[1, 2, 3]

### Booleans

In [55]:
True

True

In [56]:
False

False

### Tuples

In [57]:
a_list = [1,2,3]

In [58]:
a_list[0]

1

In [59]:
a_list[0] = 'New'

In [60]:
a_list

['New', 2, 3]

In [61]:
a_list.append(4)

In [62]:
a_list

['New', 2, 3, 4]

In [63]:
tuples = (1,2,3)

In [64]:
tuples[0]

1

In [65]:
tuples[0] = 'New'

TypeError: 'tuple' object does not support item assignment

### Sets

In [66]:
{1,2,3}

{1, 2, 3}

In [67]:
{1,2,3,1,2,3,1,2,3}

{1, 2, 3}

In [68]:
[1,1,1,1,1,2,2,2,2,2,3,3,3,3,3]

[1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3]

In [69]:
set([1,1,1,1,1,2,2,2,2,2,3,3,3,3,3])

{1, 2, 3}

In [70]:
s = {1,2,3}

In [71]:
s.add(4)

In [72]:
s

{1, 2, 3, 4}

In [73]:
s.add(5)

In [74]:
s

{1, 2, 3, 4, 5}

### Comparision Operators

In [75]:
1 > 2

False

In [76]:
1 < 2

True

In [77]:
1 >= 2

False

In [78]:
1 <= 2

True

In [79]:
1 == 1

True

In [80]:
1 == 2

False

In [81]:
1 != 2

True

In [82]:
1 < 2 and 2 > 3

False

### If, Else, Elif Statement

In [83]:
if 1<2:
    print('Yello')

Yello


In [84]:
if 1==2:
    print('Tata Nexon')
else:
    print('Tata Punch')

Tata Punch


In [85]:
if 1==2:
    print('Tata Nexon')
elif 2==2:
    print('Tata Harrier')
else:
    print('Tata Punch')

Tata Harrier


# Part 3

### Loops

In [86]:
seq = [1,2,3,4,5]

In [87]:
for items in seq:
    print('hello')

hello
hello
hello
hello
hello


In [88]:
i = 1

while i < 5:
    print('i is {}'.format(i))
    i = i+1

i is 1
i is 2
i is 3
i is 4


In [89]:
for x in seq:
    print(x)

1
2
3
4
5


In [90]:
range(5)

range(0, 5)

In [91]:
for x in range(5):
    print(x)

0
1
2
3
4


In [92]:
list(range(5))

[0, 1, 2, 3, 4]

In [1]:
x = [0, 1, 2, 3, 4]

In [2]:
out = []

for items in x:
    out.append(items**2)

In [3]:
out

[0, 1, 4, 9, 16]

In [4]:
x = [1,2,3,4,5]

In [5]:
out = [num**2 for num in x]

In [6]:
out

[1, 4, 9, 16, 25]

### Functions

In [7]:
def my_func(param1):
    print(param1)

In [9]:
my_func('Suraj')

Suraj


In [13]:
def func(name):
    print('Hello '+ name)

In [14]:
func('Suraj')

Hello Suraj


In [17]:
def square(num):
    """
    This is a docstring
    and this function squares a number
    """
    print(num**2)

In [18]:
square(4)

16


In [19]:
square(5)

25


# Part 4

### Map


In [28]:
def multiply2(num):
    print(num * 2)

In [29]:
multiply2(5)

10


In [30]:
seq = [1,2,3,4,5]

In [33]:
list(map(multiply2,seq))

2
4
6
8
10


[None, None, None, None, None]

### Lamda Expression

In [1]:
t = lambda var: var*2

In [2]:
t(6)

12

In [3]:
seq = [1,2,3,4]

In [4]:
list(map(lambda seq:seq*2,seq))

[2, 4, 6, 8]

### Filter

In [7]:
list(filter(lambda seq:seq%2==0,seq))

[2, 4]

In [8]:
s = 'Hello my name is Suraj'

In [12]:
s.lower()

'hello my name is suraj'

In [13]:
s.upper()

'HELLO MY NAME IS SURAJ'

In [14]:
s.split()

['hello', 'my', 'name', 'is', 'Suraj']

In [15]:
tweet = 'New iphone 15 is launch #apple'

In [16]:
tweet.split('#')

['New iphone 15 is launch ', 'apple']

In [17]:
tweet.split('#')[1]

'apple'

In [18]:
tweet.split('#')[0]

'New iphone 15 is launch '

In [20]:
d = {'k1':1, 'k2': 2, 'k3': 3}

In [21]:
d

{'k1': 1, 'k2': 2, 'k3': 3}

In [22]:
d.keys()

dict_keys(['k1', 'k2', 'k3'])

In [23]:
d.values()

dict_values([1, 2, 3])

In [24]:
d.items()

dict_items([('k1', 1), ('k2', 2), ('k3', 3)])

In [2]:
l = [1,2,3]

In [3]:
item = l.pop()

In [4]:
l

[1, 2]

In [5]:
item

3

In [6]:
l.append(item)

In [7]:
l

[1, 2, 3]

In [10]:
l.append(2)

In [12]:
new = (1,4,5,6,7)

In [13]:
l.append(new)

In [14]:
l

[1, 2, 3, 2, 2, (1, 4, 5, 6, 7)]

In [15]:
'x' in [1,2,3]

False

In [16]:
'x' in ['x', 'y']

True

In [17]:
x = [1,2,3,4]

In [18]:
for items in x:
    print(items)

1
2
3
4


In [19]:
x = [(1,2),(3,4)]

In [20]:
for items in x:
    print(items)

(1, 2)
(3, 4)


In [21]:
for a,b  in x:
    print(a)
    print(b)

1
2
3
4


### Numpy

In [1]:
my_list = [1,2,3]

In [2]:
import numpy as np

In [3]:
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3])

In [5]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [6]:
mat = np.array(my_mat)

In [7]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [10]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [15]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.ones(3)

array([1., 1., 1.])

In [17]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
np.linspace(0,5)

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

In [21]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [23]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
np.random.rand(5)

array([0.01173594, 0.58996024, 0.97863488, 0.58114294, 0.57236299])

In [25]:
np.random.rand(5,3)

array([[0.29004118, 0.15430201, 0.10531111],
       [0.8302438 , 0.07882011, 0.71942656],
       [0.18728887, 0.79825863, 0.47869305],
       [0.90956375, 0.70438255, 0.83181175],
       [0.21804315, 0.27329017, 0.00378479]])

In [26]:
np.random.randn(5,3)

array([[ 0.24233552,  0.96447222, -0.60061114],
       [-1.52980441, -0.95853241, -1.10057367],
       [-1.49296238, -0.03842578,  0.42701596],
       [ 0.92358171, -0.85730626,  0.33511549],
       [-0.94235637,  0.30529315, -0.42844464]])

In [31]:
np.random.randint(0,5,10)

array([1, 3, 3, 3, 1, 1, 3, 2, 4, 2])

In [32]:
arr = np.arange(25)

In [33]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [34]:
ranarr = np.random.randint(0,50,10)

In [35]:
ranarr

array([29, 30, 36, 10, 47, 29, 12, 31,  9,  9])

### Array Reshape

In [36]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [43]:
ranarr

array([29, 30, 36, 10, 47, 29, 12, 31,  9,  9])

In [40]:
ranarr.max()

47

In [41]:
ranarr.min()

9

In [42]:
ranarr.argmax()

4

In [44]:
ranarr.argmin()

8

In [46]:
ranarr.dtype

dtype('int64')

### Numpy Array Indexing

In [47]:
arr[0]

0

In [50]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [49]:
arr[4:6]

array([4, 5])

In [51]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [52]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
arr_2d[0]

array([1, 2, 3])

In [54]:
arr_2d[0][2]

3

In [57]:
arr_2d[:2,:1]

array([[1],
       [4]])

In [58]:
np_arr = np.arange(1,11)

In [59]:
np_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [61]:
np_arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [62]:
np_arr[np_arr > 5]

array([ 6,  7,  8,  9, 10])

In [63]:
arr_2d = np.arange(50).reshape(5,10)

In [64]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

### Numpy Operation

In [65]:
np_arr + np_arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [66]:
np_arr +100

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [67]:
np_arr * 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [68]:
np_arr - 1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
np_arr/np_arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [70]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721,
        0.91294525,  0.83665564, -0.00885131, -0.8462204 , -0.90557836])

In [71]:
np.log(arr)

/var/folders/m4/nx29shf56ln2wkz61pqn9qc80000gn/T/ipykernel_13161/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733,
       2.7080502 , 2.77258872, 2.83321334, 2.89037176, 2.94443898,
       2.99573227, 3.04452244, 3.09104245, 3.13549422, 3.17805383])

### Pandas